### ISSUE TITLE
kan ikke oprette token på driftmiljø

### ISSUE THREAD

**Issue by KiraH** [DBCDK/smaug-admin#17]
hvis jeg klikker på token knappen i driftmiljø'et, ser det ikke ud til der oprettes en token.

![tokenfejl](https://cloud.githubusercontent.com/assets/355018/21344560/a40e6a56-c69c-11e6-894f-5ef2487883e2.png)

**Comment by vibjerg** [comment]
Blev løst med en udrulning af smaug
